/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Chip: typeof import('./src/components/Chip.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    Restore: typeof import('./src/components/Restore.vue')['default']
    RestoreDatabase: typeof import('./src/components/RestoreDatabase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YamlBlock: typeof import('./src/components/YamlBlock.vue')['default']
    YamlViewer: typeof import('./src/components/YamlViewer.vue')['default']
  }
}
