/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/crypt/config': RouteRecordInfo<'/crypt/config', '/crypt/config', Record<never, never>, Record<never, never>>,
    '/crypt/database': RouteRecordInfo<'/crypt/database', '/crypt/database', Record<never, never>, Record<never, never>>,
    '/databases/dynamodb': RouteRecordInfo<'/databases/dynamodb', '/databases/dynamodb', Record<never, never>, Record<never, never>>,
    '/databases/mariadb': RouteRecordInfo<'/databases/mariadb', '/databases/mariadb', Record<never, never>, Record<never, never>>,
    '/databases/mongodb': RouteRecordInfo<'/databases/mongodb', '/databases/mongodb', Record<never, never>, Record<never, never>>,
    '/databases/mssql': RouteRecordInfo<'/databases/mssql', '/databases/mssql', Record<never, never>, Record<never, never>>,
    '/databases/mysql': RouteRecordInfo<'/databases/mysql', '/databases/mysql', Record<never, never>, Record<never, never>>,
    '/databases/neo4j': RouteRecordInfo<'/databases/neo4j', '/databases/neo4j', Record<never, never>, Record<never, never>>,
    '/databases/psql': RouteRecordInfo<'/databases/psql', '/databases/psql', Record<never, never>, Record<never, never>>,
    '/databases/redis': RouteRecordInfo<'/databases/redis', '/databases/redis', Record<never, never>, Record<never, never>>,
    '/databases/sqlite': RouteRecordInfo<'/databases/sqlite', '/databases/sqlite', Record<never, never>, Record<never, never>>,
    '/docker': RouteRecordInfo<'/docker', '/docker', Record<never, never>, Record<never, never>>,
    '/overview': RouteRecordInfo<'/overview', '/overview', Record<never, never>, Record<never, never>>,
    '/servers': RouteRecordInfo<'/servers', '/servers', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/shell': RouteRecordInfo<'/shell', '/shell', Record<never, never>, Record<never, never>>,
    '/storages/azure': RouteRecordInfo<'/storages/azure', '/storages/azure', Record<never, never>, Record<never, never>>,
    '/storages/backblaze': RouteRecordInfo<'/storages/backblaze', '/storages/backblaze', Record<never, never>, Record<never, never>>,
    '/storages/cloudflare': RouteRecordInfo<'/storages/cloudflare', '/storages/cloudflare', Record<never, never>, Record<never, never>>,
    '/storages/digital-ocean': RouteRecordInfo<'/storages/digital-ocean', '/storages/digital-ocean', Record<never, never>, Record<never, never>>,
    '/storages/ftp': RouteRecordInfo<'/storages/ftp', '/storages/ftp', Record<never, never>, Record<never, never>>,
    '/storages/google': RouteRecordInfo<'/storages/google', '/storages/google', Record<never, never>, Record<never, never>>,
    '/storages/local': RouteRecordInfo<'/storages/local', '/storages/local', Record<never, never>, Record<never, never>>,
    '/storages/minio': RouteRecordInfo<'/storages/minio', '/storages/minio', Record<never, never>, Record<never, never>>,
    '/storages/s3': RouteRecordInfo<'/storages/s3', '/storages/s3', Record<never, never>, Record<never, never>>,
    '/storages/sftp': RouteRecordInfo<'/storages/sftp', '/storages/sftp', Record<never, never>, Record<never, never>>,
    '/template': RouteRecordInfo<'/template', '/template', Record<never, never>, Record<never, never>>,
    '/timelines': RouteRecordInfo<'/timelines', '/timelines', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/crypt/config.vue': {
      routes: '/crypt/config'
      views: never
    }
    'src/pages/crypt/database.vue': {
      routes: '/crypt/database'
      views: never
    }
    'src/pages/databases/dynamodb.vue': {
      routes: '/databases/dynamodb'
      views: never
    }
    'src/pages/databases/mariadb.vue': {
      routes: '/databases/mariadb'
      views: never
    }
    'src/pages/databases/mongodb.vue': {
      routes: '/databases/mongodb'
      views: never
    }
    'src/pages/databases/mssql.vue': {
      routes: '/databases/mssql'
      views: never
    }
    'src/pages/databases/mysql.vue': {
      routes: '/databases/mysql'
      views: never
    }
    'src/pages/databases/neo4j.vue': {
      routes: '/databases/neo4j'
      views: never
    }
    'src/pages/databases/psql.vue': {
      routes: '/databases/psql'
      views: never
    }
    'src/pages/databases/redis.vue': {
      routes: '/databases/redis'
      views: never
    }
    'src/pages/databases/sqlite.vue': {
      routes: '/databases/sqlite'
      views: never
    }
    'src/pages/docker.vue': {
      routes: '/docker'
      views: never
    }
    'src/pages/overview.vue': {
      routes: '/overview'
      views: never
    }
    'src/pages/servers.vue': {
      routes: '/servers'
      views: never
    }
    'src/pages/settings.vue': {
      routes: '/settings'
      views: never
    }
    'src/pages/shell.vue': {
      routes: '/shell'
      views: never
    }
    'src/pages/storages/azure.vue': {
      routes: '/storages/azure'
      views: never
    }
    'src/pages/storages/backblaze.vue': {
      routes: '/storages/backblaze'
      views: never
    }
    'src/pages/storages/cloudflare.vue': {
      routes: '/storages/cloudflare'
      views: never
    }
    'src/pages/storages/digital-ocean.vue': {
      routes: '/storages/digital-ocean'
      views: never
    }
    'src/pages/storages/ftp.vue': {
      routes: '/storages/ftp'
      views: never
    }
    'src/pages/storages/google.vue': {
      routes: '/storages/google'
      views: never
    }
    'src/pages/storages/local.vue': {
      routes: '/storages/local'
      views: never
    }
    'src/pages/storages/minio.vue': {
      routes: '/storages/minio'
      views: never
    }
    'src/pages/storages/s3.vue': {
      routes: '/storages/s3'
      views: never
    }
    'src/pages/storages/sftp.vue': {
      routes: '/storages/sftp'
      views: never
    }
    'src/pages/template.vue': {
      routes: '/template'
      views: never
    }
    'src/pages/timelines.vue': {
      routes: '/timelines'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
